# -*- coding: utf-8 -*-
"""Copy of SQLpractise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15op6Aw6Oz2ilrttswb4x6IkB9lA92uYo
"""

import sqlite3

def sql_connection():
  try:
    conn = sqlite3.connect('/content/drive/MyDrive/Colab Notebooks/Database/customers.db')
    print("Connection done...Database is create")
  except:
    print("Error in creating Database")
  finally:
    if(conn):
      conn.close()
      print("Sqlite connection is closed")

  sql_connection()

def sql_connection():
  try:
    conn = sqlite3.connect('/content/drive/MyDrive/Colab Notebooks/Database/customers.db')
    return conn
  except:
    print("Error connecting to Database")

def sql_table(conn):
  cursor_obj = conn.cursor()
  cursor_obj.execute("CREATE TABLE employees1(id integer PRIMARY KEY, name text, salary real, department text, position text, hireData text)")
  conn.commit()

conn = sql_connection()
sql_table(conn)

